


spring:
  jpa:
    database: MYSQL
    showSql: true
    generateDdl: true
    hibernate:
      ddlAuto: update
      namingStrategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      
  datasource:
    username: root
    password: 
    url: jdbc:mysql://127.0.0.1/liquibasedb?serverTimezone=GMT%2B8&useSSL=true&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    
  liquibase:
    changeLog: classpath:/db/changelog.xml
    enabled: false

server:
  port: 8082
